### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by treyhunner**
I think all code should have tests.

The tests shouldn't depend on the Authorize.NET servers so [mock][] should probably be used to mock calls to `request.post` and other network calls as needed.

I may turn this into a pull request if I decide to start writing some tests.

Goals of this PR:
- [x] Add basic test suite allowing `python setup.py test` to work
- [x] Add a few example tests
- [x] Add tox file for supported Python/Django versions
- [x] Add Travis and Coveralls support

### CODE REVIEW

**Comment by andrew-kurin** [comment]
Yes, either [mock](https://pypi.python.org/pypi/mock) or [httmock](https://github.com/patrys/httmock) (from #22), whatever makes more sense.

**Comment by treyhunner** [comment]
I converted this to a pull request and added a checklist to the description.

Which Python/Django versions should be tested?  The current tox file I've added tests Python 2.6 and 2.7 and Django 1.4, 1.5, and trunk.

**Comment by andrew-kurin** [comment]
Yes. Supporting those versions seems reasonable to me. We need Python
2.6 since it goes by default on current version of Amazon Linux. And
hopefully supporting two versions of Django would be enough.

**Comment by treyhunner** [comment]
@zen4ever can you enable the repository on Travis CI?  Travis adds a post-receive hook on Github which requires admin access to add.

**Comment by andrew-kurin** [comment]
@treyhunner should be enabled now

**Comment by treyhunner** [comment]
I went with httmock because it's simple.

I added a couple example tests including a test for one of the add_profile success cases.

I added Travis and Coveralls badges to the README file.  I can remove that commit if you don't like showing those in the README.

I disabled the coveralls comments on pull requests (they happen on every push which can get annoying).

I think this is ready to be merged now.  There are very few tests currently, but some tests are better than none.

**Comment by andrew-kurin** [comment]
Looks good. Feel free to merge it. I will try to add some more tests later.

**Pull request merged**
